[package]
name = "books"
version = "0.1.0"
edition = "2021"

[dependencies]
ryde = { version = "0.3.0", path = "../ryde" }
serde = { version = "1.0.203", features = ["derive"] }
tower-http = { version = "0.5.2", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = "0.3.0"
